# Lucius libsai package

LEMMINGSAI_VERSION = 1.0-3
LEMMINGSAI_LIB_NAME = lucius-libsai
LEMMINGSAI_LIB_DIR = src/libsai-grpc

ALPINE_SRC_PATH = platform/alpinevs
LEMMINGSAI = $(LEMMINGSAI_LIB_NAME)_$(LEMMINGSAI_VERSION)_$(CONFIGURED_ARCH).deb
$(LEMMINGSAI)_SRC_PATH = $(ALPINE_SRC_PATH)/$(LEMMINGSAI_LIB_DIR)
SONIC_DPKG_DEBS += $(LEMMINGSAI)
