# Lucius packet handler for Alpine

ALPINE_SRC_PATH=platform/alpinevs
PKT_HANDLER = lucius-pkthandler_1.0-2_$(CONFIGURED_ARCH).deb
$(PKT_HANDLER)_SRC_PATH = $(ALPINE_SRC_PATH)/src/services/pkt-handler
$(PKT_HANDLER)_DEPENDS += $(LIBNL3_DEV) $(LIBNL_GENL3_DEV)

$(PKT_HANDLER)_DEPENDS += $(ALPINE_CONFIG)
$(PKT_HANDLER)_DEPENDS += $(ALPINE_INIT)
$(PKT_HANDLER)_DEPENDS += $(ALPINE_PLATFORM)

$(PKT_HANDLER)_RDEPENDS += $(LIBNL3) $(LIBNL_GENL3)
SONIC_DPKG_DEBS += $(PKT_HANDLER)
