{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files, rsync_from_builder_stage %}
ARG BASE=docker-swss-layer-trixie-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

FROM $BASE AS base

ARG docker_container_name

COPY ["etc/rsyslog.conf", "/etc/rsyslog.conf"]
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y gnupg

RUN apt-get install -y net-tools \
                       iproute2 \
                       arping \
                       ndisc6 \
                       ethtool \
                       tcpdump \
                       ifupdown \
                       bridge-utils \
                       libjudydebian1 \
                       openssh-client \
                       openssh-server \
                       libc-ares2 \
                       bash-completion \
                       logrotate \
                       apt-utils \
                       psmisc \
                       python3-scapy \
                       conntrack \
                       iptables \
                       jq \
                       uuid-dev \
                       build-essential \
                       python3-dev \
                       python3-gi \
                       libssl-dev \
                       swig \
                       openssl \
                       libcairo2-dev \
                       libdbus-1-dev \
                       libgirepository1.0-dev \
                       libsystemd-dev \
                       pkg-config \
                       gir1.2-glib-2.0 \
                       libdbus-1-3 \
                       libgirepository-1.0-1 \
                       {%- if ENABLE_ASAN == "y" %}
                       libasan6 \
                       {%- endif %}
                       dbus \
                       redis-server \
                       libprotobuf-c-dev \
                       protobuf-c-compiler \
                       libgoogle-glog-dev \
                       libgrpc++1.51t64 \
                       libgrpc29t64 \
                       libprotobuf32t64 \
                       libgrpc++-dev \
                       libgrpc-dev \
                       libzmq5 \
                       protobuf-compiler \
                       protobuf-compiler-grpc \
                       python3-protobuf \
                       python3-grpcio

RUN pip3 install pyangbind==0.8.1
RUN pip3 uninstall -y enum34

RUN pip3 install \
         pyroute2==0.7.2 \
         netifaces==0.11.0

RUN pip3 install meson-python meson ninja patchelf

{% if docker_sonic_alpinevs_debs.strip() -%}
{{ copy_files("debs/", docker_sonic_alpinevs_debs.split(' '), "/debs/") }}
{{ install_debian_packages(docker_sonic_alpinevs_debs.split(' ')) }}
{%- endif %}

{% if docker_sonic_alpinevs_pydebs.strip() -%}
{{ copy_files("python-debs/", docker_sonic_alpinevs_pydebs.split(' '), "/debs/") }}
{{ install_debian_packages(docker_sonic_alpinevs_pydebs.split(' ')) }}
{%- endif %}

{% if docker_sonic_alpinevs_whls.strip() %}
{{ copy_files("python-wheels/", docker_sonic_alpinevs_whls.split(' '), "/python-wheels/") }}
{{ install_python_wheels(docker_sonic_alpinevs_whls.split(' ')) }}
{% endif %}

RUN apt-get purge -y build-essential libssl-dev swig python3-dev
RUN apt-get purge -y libcairo2-dev libdbus-1-dev libgirepository1.0-dev libsystemd-dev pkg-config
RUN apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y
RUN pip3 uninstall -y meson-python meson ninja patchelf
RUN rm -rf /debs ~/.cache

RUN sed -ri 's/^# save ""$/save ""/g;                    \
             s/^daemonize yes$/daemonize no/;            \
             s/^logfile .*$/logfile ""/;                 \
             s/^# syslog-enabled no$/syslog-enabled no/; \
             s/^# unixsocket/unixsocket/;                \
             s/redis-server.sock/redis.sock/g;           \
             s/^client-output-buffer-limit pubsub [0-9]+mb [0-9]+mb [0-9]+/client-output-buffer-limit pubsub 0 0 0/; \
             s/^notify-keyspace-events ""$/notify-keyspace-events AKE/; \
             s/^databases [0-9]+$/databases 100/ \
            ' /etc/redis/redis.conf

COPY ["50-default.conf", "/etc/rsyslog.d/"]
COPY ["start.sh", "orchagent.sh", "telemetry.sh", "files/update_chassisdb_config", "/usr/bin/"]
COPY ["alpinevs-script.sh", "alpinevs-healthcheck.sh", "p4rt.sh", "bin/alpinevs-init.sh","bin/alpinevs-config.sh","bin/pkt-handler", "/usr/bin/"]
COPY ["start.sh", "orchagent.sh", "telemetry.sh", "files/update_chassisdb_config", "/usr/bin/"]
COPY ["alpinevs-script.sh", "alpinevs-healthcheck.sh", "p4rt.sh", "bin/alpinevs-init.sh","bin/alpinevs-config.sh","bin/pkt-handler", "/usr/bin/"]
COPY ["supervisord.conf.j2", "/usr/share/sonic/templates/"]
COPY ["p4rt_vars.j2", "telemetry_vars.j2", "/usr/share/sonic/templates/"]
COPY ["files/configdb-load.sh", "/usr/bin/"]
COPY ["files/arp_update", "/usr/bin/"]
COPY ["files/buffers_config.j2", "files/qos_config.j2", "files/arp_update_vars.j2", "files/copp_cfg.j2", "/usr/share/sonic/templates/"]
COPY ["files/sonic_version.yml", "/etc/sonic/"]
COPY ["port_breakout_config_db.json", "/etc/sonic/"]
COPY ["database_config.json", "/etc/default/sonic-db/"]
COPY ["hostname.j2", "/usr/share/sonic/templates/"]
COPY ["init_cfg.json.j2", "/usr/share/sonic/templates/"]
COPY ["config_db.json", "/etc/sonic/"]
COPY ["default_chassis_cfg.json", "/etc/default/sonic-db/"]
COPY ["asic_table.json", "/etc/sonic/"]
COPY ["zero_profiles.json", "/etc/sonic"]
COPY ["buffermgrd.sh", "/usr/bin/"]

# Copy the entire device hardware profile directory structure
COPY ["device/", "/usr/share/sonic/device/"]

RUN mkdir -p /etc/supervisor/conf.d/
RUN sonic-cfggen -a "{\"ENABLE_ASAN\":\"{{ENABLE_ASAN}}\"}" -t /usr/share/sonic/templates/supervisord.conf.j2 > /etc/supervisor/conf.d/supervisord.conf
RUN rm -f /usr/share/sonic/templates/supervisord.conf.j2

{%- if ENABLE_ASAN == "y" %}
RUN mkdir -p /var/log/asan
{%- endif %}

RUN echo "docker-sonic-alpinevs" > /etc/hostname

FROM $BASE

{{ rsync_from_builder_stage() }}

# Create /zmq_swss directory for ZMQ IPC sockets
RUN mkdir -p /zmq_swss

# Create the sock directory for p4rt's use
RUN mkdir -p /sock

RUN mkdir -p /var/run/sshd

RUN sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    echo "root:google" | chpasswd && \
    useradd -m -s /bin/bash admin && \
    echo "admin:google" | chpasswd && \
    echo "admin ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

COPY sshd.conf /etc/supervisor/conf.d/sshd.conf

ENV PLATFORM=x86_64-kvm_x86_64-r0
ENV HWSKU=alpinevs

ENTRYPOINT ["/usr/local/bin/supervisord"]
