#!/bin/bash -e
# Script to be run on AlpineVS switch on init

if [ -f /etc/sonic/config_db.json ]; then
    platform=$(grep -oP '"hwsku": "([^"]*)"' /etc/sonic/config_db.json | cut -d'"' -f 4)

    # Add chassis info in StateDB
    redis-cli -n 6 hmset "CHASSIS_INFO|chassis" "serial" "Alpine00"

    case "${platform}" in
    "alpine_vs")
    redis-cli -n 6 hmset "CHASSIS_INFO|chassis" "product_name" "alpine_vs"
    redis-cli -n 6 hmset "CHASSIS_INFO|chassis" "cpu-type" "unset"
    ;;

    *)
    redis-cli -n 6 hmset "CHASSIS_INFO|chassis" "platform" "generic"
    redis-cli -n 6 hmset "CHASSIS_INFO|chassis" "cpu-type" "unset"
    ;;

    esac

    redis-cli -n 4 hmset "PORT|Ethernet0" "id" "1"
    redis-cli -n 4 hmset "PORT|Ethernet4" "id" "2"
    redis-cli -n 4 hmset "PORT|Ethernet8" "id" "7"

    echo "Setting transceiver info for "${platform}""
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet0" "parent" "1/1"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet4" "parent" "1/2"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet8" "parent" "1/3"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet12" "parent" "1/4"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet16" "parent" "1/5"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet20" "parent" "1/6"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet24" "parent" "1/7"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet28" "parent" "1/8"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet32" "parent" "1/9"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet36" "parent" "1/10"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet40" "parent" "1/11"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet44" "parent" "1/12"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet48" "parent" "1/13"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet52" "parent" "1/14"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet56" "parent" "1/15"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet60" "parent" "1/16"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet64" "parent" "1/17"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet68" "parent" "1/18"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet72" "parent" "1/19"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet76" "parent" "1/20"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet80" "parent" "1/21"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet84" "parent" "1/22"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet88" "parent" "1/23"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet92" "parent" "1/24"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet96" "parent" "1/25"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet100" "parent" "1/26"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet104" "parent" "1/27"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet108" "parent" "1/28"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet112" "parent" "1/29"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet116" "parent" "1/30"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet120" "parent" "1/31"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet124" "parent" "1/32"

    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet0" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet4" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet8" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet12" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet16" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet20" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet24" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet28" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet32" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet36" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet40" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet44" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet48" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet52" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet56" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet60" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet64" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet68" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet72" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet76" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet80" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet84" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet88" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet92" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet96" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet100" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet104" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet108" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet112" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet116" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet120" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet124" "type" "OSFP 8X Pluggable Transceiver"

    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet0" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet4" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet8" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet12" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet16" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet20" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet24" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet28" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet32" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet36" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet40" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet44" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet48" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet52" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet56" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet60" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet64" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet68" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet72" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet76" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet80" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet84" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet88" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet92" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet96" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet100" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet104" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet108" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet112" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet116" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet120" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet124" "status" "1"

    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet0" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet4" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet8" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet12" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet16" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet20" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet24" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet28" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet32" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet36" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet40" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet44" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet48" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet52" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet56" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet60" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet64" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet68" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet72" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet76" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet80" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet84" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet88" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet92" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet96" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet100" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet104" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet108" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet112" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet116" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet120" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet124" "module_state" "ModuleReady"

fi

# ADD PORT_TABLE:CPU in APPL_STATE_DB.
redis-cli -n 14 hmset "PORT_TABLE:CPU" "NULL" "NULL"
