#!/bin/bash -e
# Script to be run on AlpineVS switch on init

if [ -f /etc/sonic/config_db.json ]; then
    platform=$(grep -oP '"hwsku": "([^"]*)"' /etc/sonic/config_db.json | cut -d'"' -f 4)

    # ADD PORT_TABLE:CPU in APPL_STATE_DB.
    redis-cli -n 14 hmset "PORT_TABLE:CPU" "NULL" "NULL"

    # Add chassis info in StateDB
    redis-cli -n 6 hmset "CHASSIS_INFO|chassis" "serial" "Alpine00"

    case "${platform}" in
    "alpine_vs")
    redis-cli -n 6 hmset "CHASSIS_INFO|chassis" "product_name" "alpine_vs"
    redis-cli -n 6 hmset "CHASSIS_INFO|chassis" "cpu-type" "unset"
    ;;

    *)
    redis-cli -n 6 hmset "CHASSIS_INFO|chassis" "platform" "generic"
    redis-cli -n 6 hmset "CHASSIS_INFO|chassis" "cpu-type" "unset"
    ;;

    esac


    if [ "$platform" == "alpine_switch5" ]; then
        redis-cli -n 4 hmset "PORT|Ethernet1/1/1" "id" "1"
        redis-cli -n 4 hmset "PORT|Ethernet1/2/1" "id" "2"
        redis-cli -n 4 hmset "PORT|Ethernet1/3/1" "id" "3"
        redis-cli -n 4 hmset "PORT|Ethernet1/4/1" "id" "4"
        redis-cli -n 4 hmset "PORT|Ethernet1/5/1" "id" "5"
        redis-cli -n 4 hmset "PORT|Ethernet1/6/1" "id" "6"
        redis-cli -n 4 hmset "PORT|Ethernet1/7/1" "id" "7"
        redis-cli -n 4 hmset "PORT|Ethernet1/8/1" "id" "8"
        redis-cli -n 4 hmset "PORT|Ethernet1/9/1" "id" "9"
        redis-cli -n 4 hmset "PORT|Ethernet1/10/1" "id" "10"
        redis-cli -n 4 hmset "PORT|Ethernet1/11/1" "id" "11"
        redis-cli -n 4 hmset "PORT|Ethernet1/12/1" "id" "12"
        redis-cli -n 4 hmset "PORT|Ethernet1/13/1" "id" "13"
        redis-cli -n 4 hmset "PORT|Ethernet1/14/1" "id" "14"
        redis-cli -n 4 hmset "PORT|Ethernet1/15/1" "id" "15"
        redis-cli -n 4 hmset "PORT|Ethernet1/16/1" "id" "16"
        redis-cli -n 4 hmset "PORT|Ethernet1/17/1" "id" "17"
        redis-cli -n 4 hmset "PORT|Ethernet1/18/1" "id" "18"
        redis-cli -n 4 hmset "PORT|Ethernet1/19/1" "id" "19"
        redis-cli -n 4 hmset "PORT|Ethernet1/20/1" "id" "20"
        redis-cli -n 4 hmset "PORT|Ethernet1/21/1" "id" "21"
        redis-cli -n 4 hmset "PORT|Ethernet1/22/1" "id" "22"
        redis-cli -n 4 hmset "PORT|Ethernet1/23/1" "id" "23"
        redis-cli -n 4 hmset "PORT|Ethernet1/24/1" "id" "24"
        redis-cli -n 4 hmset "PORT|Ethernet1/25/1" "id" "25"
        redis-cli -n 4 hmset "PORT|Ethernet1/26/1" "id" "26"
        redis-cli -n 4 hmset "PORT|Ethernet1/27/1" "id" "27"
        redis-cli -n 4 hmset "PORT|Ethernet1/28/1" "id" "28"
        redis-cli -n 4 hmset "PORT|Ethernet1/29/1" "id" "29"
        redis-cli -n 4 hmset "PORT|Ethernet1/30/1" "id" "30"
        redis-cli -n 4 hmset "PORT|Ethernet1/31/1" "id" "31"
        redis-cli -n 4 hmset "PORT|Ethernet1/32/1" "id" "32"
        redis-cli -n 4 hmset "PORT|Ethernet1/1/5" "id" "51"
        redis-cli -n 4 hmset "PORT|Ethernet1/2/5" "id" "52"
        redis-cli -n 4 hmset "PORT|Ethernet1/3/5" "id" "53"
        redis-cli -n 4 hmset "PORT|Ethernet1/4/5" "id" "54"
        redis-cli -n 4 hmset "PORT|Ethernet1/5/5" "id" "55"
        redis-cli -n 4 hmset "PORT|Ethernet1/6/5" "id" "56"
        redis-cli -n 4 hmset "PORT|Ethernet1/7/5" "id" "57"
        redis-cli -n 4 hmset "PORT|Ethernet1/8/5" "id" "58"
        redis-cli -n 4 hmset "PORT|Ethernet1/9/5" "id" "59"
        redis-cli -n 4 hmset "PORT|Ethernet1/10/5" "id" "510"
        redis-cli -n 4 hmset "PORT|Ethernet1/11/5" "id" "511"
        redis-cli -n 4 hmset "PORT|Ethernet1/12/5" "id" "512"
        redis-cli -n 4 hmset "PORT|Ethernet1/13/5" "id" "513"
        redis-cli -n 4 hmset "PORT|Ethernet1/14/5" "id" "514"
        redis-cli -n 4 hmset "PORT|Ethernet1/15/5" "id" "515"
        redis-cli -n 4 hmset "PORT|Ethernet1/16/5" "id" "516"
        redis-cli -n 4 hmset "PORT|Ethernet1/17/5" "id" "517"
        redis-cli -n 4 hmset "PORT|Ethernet1/18/5" "id" "518"
        redis-cli -n 4 hmset "PORT|Ethernet1/19/5" "id" "519"
        redis-cli -n 4 hmset "PORT|Ethernet1/20/5" "id" "520"
        redis-cli -n 4 hmset "PORT|Ethernet1/21/5" "id" "521"
        redis-cli -n 4 hmset "PORT|Ethernet1/22/5" "id" "522"
        redis-cli -n 4 hmset "PORT|Ethernet1/23/5" "id" "523"
        redis-cli -n 4 hmset "PORT|Ethernet1/24/5" "id" "524"
        redis-cli -n 4 hmset "PORT|Ethernet1/25/5" "id" "525"
        redis-cli -n 4 hmset "PORT|Ethernet1/26/5" "id" "526"
        redis-cli -n 4 hmset "PORT|Ethernet1/27/5" "id" "527"
        redis-cli -n 4 hmset "PORT|Ethernet1/28/5" "id" "528"
        redis-cli -n 4 hmset "PORT|Ethernet1/29/5" "id" "529"
        redis-cli -n 4 hmset "PORT|Ethernet1/30/5" "id" "530"
        redis-cli -n 4 hmset "PORT|Ethernet1/31/5" "id" "531"
        redis-cli -n 4 hmset "PORT|Ethernet1/32/5" "id" "532"
    fi


    echo "Setting transceiver info for "${platform}""
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet1" "parent" "1/1"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet2" "parent" "1/2"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet3" "parent" "1/3"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet4" "parent" "1/4"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet5" "parent" "1/5"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet6" "parent" "1/6"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet7" "parent" "1/7"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet8" "parent" "1/8"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet9" "parent" "1/9"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet10" "parent" "1/10"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet11" "parent" "1/11"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet12" "parent" "1/12"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet13" "parent" "1/13"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet14" "parent" "1/14"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet15" "parent" "1/15"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet16" "parent" "1/16"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet17" "parent" "1/17"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet18" "parent" "1/18"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet19" "parent" "1/19"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet20" "parent" "1/20"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet21" "parent" "1/21"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet22" "parent" "1/22"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet23" "parent" "1/23"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet24" "parent" "1/24"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet25" "parent" "1/25"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet26" "parent" "1/26"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet27" "parent" "1/27"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet28" "parent" "1/28"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet29" "parent" "1/29"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet30" "parent" "1/30"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet31" "parent" "1/31"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet32" "parent" "1/32"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet1" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet2" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet3" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet4" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet5" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet6" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet7" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet8" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet9" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet10" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet11" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet12" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet13" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet14" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet15" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet16" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet17" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet18" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet19" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet20" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet21" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet22" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet23" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet24" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet25" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet26" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet27" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet28" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet29" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet30" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet31" "type" "OSFP 8X Pluggable Transceiver"
    redis-cli -n 6 hmset "TRANSCEIVER_INFO|Ethernet32" "type" "OSFP 8X Pluggable Transceiver"

    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet1" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet2" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet3" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet4" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet5" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet6" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet7" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet8" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet9" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet10" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet11" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet12" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet13" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet14" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet15" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet16" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet17" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet18" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet19" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet20" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet21" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet22" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet23" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet24" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet25" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet26" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet27" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet28" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet29" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet30" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet31" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet32" "status" "1"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet33" "status" "0"
    redis-cli -n 6 hmset "TRANSCEIVER_STATUS|Ethernet34" "status" "0"

    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet1" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet2" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet3" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet4" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet5" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet6" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet7" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet8" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet9" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet10" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet11" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet12" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet13" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet14" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet15" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet16" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet17" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet18" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet19" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet20" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet21" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet22" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet23" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet24" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet25" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet26" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet27" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet28" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet29" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet30" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet31" "module_state" "ModuleReady"
    redis-cli -n 6 hmset "TRANSCEIVER_DOM_SENSOR|Ethernet32" "module_state" "ModuleReady"

fi
